import numpy as np
import pandas as pd

import seaborn as sns
import matplotlib.pyplot as plt

from bk import plot
from typing import Union, Optional,Tuple, Dict, Sequence

from statannotations.Annotator import Annotator
from settings import colors

def set_rem_labels(df):
    rem_on = df.pInc <= 0.001
    rem_off = df.pDec <= 0.001
    rem_unknown = ((df.pInc > 0.001) & (df.pDec > 0.001))

    df['REM_label'] = np.nan
    df['REM_label'][rem_on] = 'REM_ON'
    df['REM_label'][rem_off] = 'REM_OFF'
    df['REM_label'][rem_unknown] = 'Unknown'

    return df


def boxenplot_firing_rates(df,stru,ax = None):

    if ax is None:
        fig,ax = plt.subplots()

    states = ['REM','NREM','WAKE_HOMECAGE']
    pairs = [[('Pyr', 'NREM'), ('Pyr', 'REM')],
             [('Pyr', 'NREM'), ('Pyr', 'WAKE_HOMECAGE')],
             [('Pyr', 'REM'), ('Pyr', 'WAKE_HOMECAGE')],

             [('Int', 'NREM'), ('Int', 'REM')],
             [('Int', 'NREM'), ('Int', 'WAKE_HOMECAGE')],
             [('Int', 'REM'), ('Int', 'WAKE_HOMECAGE')]]

    df_stru = df[(df.Region == stru)]

    df_melt = pd.melt(df_stru,value_vars=states,value_name='FR',id_vars = 'Type',var_name='States')
    df_melt['FR'] = np.log10(df_melt['FR'])
    df_melt['FR'].replace([np.inf,-np.inf],np.nan,inplace=True)
    df_melt.dropna(inplace=True)

    
        
    
    ### Violin plots
    ax.set_title('Violin Plots')
    plotting_params = {'data':df_melt,
                       'x':'Type',
                       'y':'FR',
                       'hue':'States',
                       'hue_order':['NREM','REM','WAKE_HOMECAGE'],
                       'palette':[colors['NREM'], colors['REM'], colors['WAKE_HOMECAGE']],
                       'ax':ax}

    sns.boxenplot(**plotting_params)
    annotator = Annotator(pairs = pairs,**plotting_params)
    annotator.configure(test="Wilcoxon",comparisons_correction = 'Bonferroni').apply_and_annotate()
    ax.set_xlabel('States')
    ax.set_ylabel('FiringRates')
    y_ticks = np.arange(-3,4)
    plt.yticks(y_ticks,pow(10.0,y_ticks))
    ax.legend(loc = 'lower right')

    return ax

def cumsum_curves_firing_rates(df,stru,states_name,ax = None):
    df_stru = df[(df.Region == stru)]
    df_pyr= df_stru[(df.Type == 'Pyr')]
    df_int = df_stru[(df.Type == 'Int')]
    
    
    if ax is None:
        fig,ax = plt.subplots(1,2)
    for state in states_name:
        fr_pyr = df_pyr[state]
        fr_int = df_int[state]
        ax[0].plot(np.sort(fr_pyr),range(len(fr_pyr)),c = colors[state])
        ax[1].plot(np.sort(fr_int),range(len(fr_int)),c = colors[state])
    
    ax[0].semilogx()
    ax[0].set_yticks(np.arange(0,2001,500))
    ax[0].set_xlim(-3,3)
    
    ax[1].set_yticks(np.arange(0,301,100))
    ax[1].set_xlim(0,fr_int.max())
    
def proportion_rem_on(df,stru,ax = None):
    if ax is None:
        fig,ax = plt.subplots()
    df = df[(df.Region == stru)]
    
    data = df.groupby(['Region','Type'])['REM_label'].value_counts(normalize = True).unstack()
    data = data[['REM_ON','REM_OFF','Unknown']]
    data = data.loc['BLA']
    print(data)
    bar = data.plot.bar(stacked = True,ax = ax,color = colors)


if __name__ == '__main__':
    df = pd.read_csv('processed_data/states_fr.csv') # generated by fr_states.py
    rem_on_off = pd.read_csv('processed_data/rem_on.csv')
    rem_on_off = set_rem_labels(rem_on_off)
    
    states_name = ['NREM','REM','WAKE_HOMECAGE']

    fig,ax = plt.subplot_mosaic("""AAAADD
                                   BBCCEE""",figsize = (16,8))
    
    
    boxenplot_firing_rates(df,'BLA',ax = ax['A'])
    cumsum_curves_firing_rates(df,'BLA',states_name = states_name,ax = (ax['B'],ax['C']))
    proportion_rem_on(rem_on_off,'BLA',ax['D'])
    plt.tight_layout()
    
    
    plt.savefig('plots/figures/fr.svg')
    plt.ion()