import numpy as np
import pandas as pd

import seaborn as sns
import matplotlib.pyplot as plt

from bk import plot
from typing import Union, Optional,Tuple, Dict, Sequence

from statannotations.Annotator import Annotator
from settings import colors

def boxenplot_firing_rates(df,stru,ax = None):

    if ax is None:
        fig,ax = plt.subplots()

    states = ['REM','NREM','WAKE_HOMECAGE']
    pairs = [[('Pyr', 'NREM'), ('Pyr', 'REM')],
             [('Pyr', 'NREM'), ('Pyr', 'WAKE_HOMECAGE')],
             [('Pyr', 'REM'), ('Pyr', 'WAKE_HOMECAGE')],

             [('Int', 'NREM'), ('Int', 'REM')],
             [('Int', 'NREM'), ('Int', 'WAKE_HOMECAGE')],
             [('Int', 'REM'), ('Int', 'WAKE_HOMECAGE')]]

    df_stru = df[(df.Region == stru)]

    df_melt = pd.melt(df_stru,value_vars=states,value_name='FR',id_vars = 'Type',var_name='States')
    df_melt['FR'] = np.log10(df_melt['FR'])
    df_melt['FR'].replace([np.inf,-np.inf],np.nan,inplace=True)
    df_melt.dropna(inplace=True)

    
        
    
    ### Violin plots
    ax.set_title('Violin Plots')
    plotting_params = {'data':df_melt,
                       'x':'Type',
                       'y':'FR',
                       'hue':'States',
                       'hue_order':['NREM','REM','WAKE_HOMECAGE'],
                       'palette':[colors['NREM'], colors['REM'], colors['WAKE_HOMECAGE']],
                       'ax':ax}

    sns.boxenplot(**plotting_params)
    annotator = Annotator(pairs = pairs,**plotting_params)
    annotator.configure(test="Wilcoxon",comparisons_correction = 'Bonferroni').apply_and_annotate()
    ax.set_xlabel('States')
    ax.set_ylabel('FiringRates')
    y_ticks = np.arange(-3,4)
    plt.yticks(y_ticks,pow(10.0,y_ticks))
    ax.legend(loc = 'lower right')

    return ax


if __name__ == '__main__':
    df = pd.read_csv('processed_data/states_fr.csv') # generated by fr_states.py
    
    boxenplot_firing_rates(df,'BLA')
    plt.ion()