import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

from bk import io, plot
from settings import oscillations_bands_mod


def label_df(df,treshold_pvalue,treshold_mrl,band):
    df = df.copy()
    mod_mask = (df[f'pvalue_{band}'] < treshold_pvalue) & (df[f'MRL_{band}'] > treshold_mrl)
    
    df[f'mod_{band}'] = np.nan
    df[f'mod_{band}'][mod_mask] = True
    df[f'mod_{band}'][~mod_mask] = False

    return df


def plot_distrib_neuron(data,state,band_name,idx,ax):
    x = data[state][band_name]['bin'][idx,:]
    y = data[state][band_name]['phases_distributions'][idx,:]
    p = data[state][band_name]['pvalue'][idx]
    mrl = data[state][band_name]['mrl'][idx]
    ax.bar(x,y,x[1]-x[0],color = 'red')
    if (p < 0.01) & (mrl > 0.04):
        ax.set_facecolor('lightgreen')
    return ax 
if __name__ == '__main__':
    stru = 'BLA'

    plt.ion()
    df = pd.read_csv('processed_data/states_fr.csv') # generated by fr_states.
    oscillations_mod = io.load_shelve('processed_data/oscillations_modulation')['merged_sessions']
    df = pd.merge(oscillations_mod['metadata'],df,on=['Rat','Day','Shank','Id','Region','Type'])
    data = oscillations_mod['mod_features']

    # combinations = [['NREM','sigma'],
    #                 ['NREM','high_gamma'],
    #                  ['REM','theta'],
    #                  ['REM','high_gamma'],
    #                  ['WAKE_HOMECAGE','theta'],
    #                  ['WAKE_HOMECAGE','mid_gamma']]
    
    # fig = plt.figure(figsize = (12,8))

    # j = 1
    # df_stru_pyr = df[(df.Region == stru) & (df.Type == 'Int')]
    # best = np.random.randint(0,len(df_stru_pyr),5)
    # for state,band in combinations:
    #     print(state,band)
    #     df['pvalue'] = data[state][band]['pvalue']
    #     df['mrl'] = data[state][band]['mrl']
        
    #     # best = np.argsort(df_stru_pyr['mrl'].values)[-5:]
    #     for i in best:
    #         idx = df_stru_pyr.iloc[i].name
    #         print('MRL:',data[state][band]['mrl'][idx])
    #         ax = plt.subplot(6,5,j, projection='polar')
    #         plot_distrib_neuron(data,state,band,idx,ax)
    #         if j<6:
    #             ax.set_title(f'#{idx}')
    #         j+=1
        
    # plt.tight_layout()
    # plt.savefig('output.png')
    # plt.savefig('mod_example_int.svg')
    # plt.close('all')

    fig,ax = plt.subplots(3,len(oscillations_bands_mod),figsize = (12,12),layout = 'tight')

    for i, (state,features) in enumerate(data.items()):
        for j,(band,freq) in enumerate(oscillations_bands_mod.items()):
            df[f'MRL_{band}'] = features[band]['mrl']
            df[f'pvalue_{band}'] = features[band]['pvalue']
            df = label_df(df,0.01,0.04,band)


            df_group = df.groupby(['Region','Type'])[f'mod_{band}'].value_counts(normalize = True).unstack()
            print(state,band,df_group.loc[stru][True][['Pyr','Int']])
            df_group = df_group.loc[stru][True][['Pyr','Int']]
            bar = df_group.plot.bar(ax = ax[i,j])
                        
            # sns.boxplot(data = df[df.Region == stru][['Type',f'MRL_{band}']],ax[i,j])
            ax[i,j].set_title(band)
            ax[i,j].set_ylabel(f'Proportion {state}')
        df_pyr = df[(df.Region == stru) & (df.Type == 'Pyr')]
        df_pyr.to_csv(state)

    
    for axe in ax.flatten(): 
        axe.set_ylim(0,1)
        plot.clean_axes(axe)

    plt.savefig('output.png')
    # plt.savefig('plots/figures/mod.svg')
    # plt.close('all')



    
